/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trackmodel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;

/**
 *
 * @author Gowest
 */
public class MurphFrame extends javax.swing.JFrame {

    private TrackModelFrame tmf;
    private JTable blocks, crossings;

    /**
     * Creates new form MurphFrame
     */
    public MurphFrame(TrackModelFrame tmf, JTable blocks, JTable crossings) {
        initComponents();
        this.tmf = tmf;
        this.blocks = blocks;
        this.crossings = crossings;
        if (TrackModel.doTablesExist()) {
            populateDropdown();
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Track Model Failure Tests");
        setResizable(false);

        jComboBox1.setMaximumRowCount(24);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Block 1", "Block 2", "Block 3", "Block 4", "Block 5" }));

        jButton1.setText("Broken Rail");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Block:");

        jButton2.setText("Track Circuit Failure");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Power Failure");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        breakSomething();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        breakSomething();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        breakSomething2();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void populateDropdown() {
        ArrayList<String> blockList = new ArrayList<>();
        try {
            Class.forName("org.sqlite.JDBC");

            Connection conn = DriverManager.getConnection("jdbc:sqlite:test.db");
            Statement stat = conn.createStatement();

            ResultSet rs = stat.executeQuery("SELECT * FROM BLOCKS;");
            while (rs.next()) {
                blockList.add("Line: " + rs.getString(1) + ", Section: " + rs.getString(2) + ", Block: " + rs.getInt(3));
            }
            jComboBox1.setModel(new DefaultComboBoxModel(blockList.toArray()));
            conn.close();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(MurphFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void breakSomething() {
        String line = jComboBox1.getSelectedItem().toString().split(",")[0];
        line = line.substring(line.lastIndexOf(" "), line.length()).trim();
        String block = jComboBox1.getSelectedItem().toString().split(",")[2];
        block = block.substring(block.lastIndexOf(" "), block.length()).trim();

        for (int i = 0; i < blocks.getRowCount(); i++) {
            if (blocks.getValueAt(i, 2).toString().equalsIgnoreCase(block) && blocks.getValueAt(i, 0).toString().equalsIgnoreCase(line)) {
                blocks.setValueAt(true, i, 9);
            }
        }
        for (int i = 0; i < crossings.getRowCount(); i++) {
            if (crossings.getValueAt(i, 2).toString().equalsIgnoreCase(block) && crossings.getValueAt(i, 0).toString().equalsIgnoreCase(line)) {
                crossings.setValueAt(true, i, 4);
                crossings.setValueAt(true, i, 5);
            }
        }
        tmf.scanOccupiedBlocks();
    }
    
    private void breakSomething2() {
        String line = jComboBox1.getSelectedItem().toString().split(",")[0];
        line = line.substring(line.lastIndexOf(" "), line.length()).trim();
        String block = jComboBox1.getSelectedItem().toString().split(",")[2];
        block = block.substring(block.lastIndexOf(" "), block.length()).trim();

        for (int i = 0; i < blocks.getRowCount(); i++) {
            if (blocks.getValueAt(i, 2).toString().equalsIgnoreCase(block) && blocks.getValueAt(i, 0).toString().equalsIgnoreCase(line)) {
                blocks.setValueAt("OUTAGE", i, 8);
            }
        }
        tmf.scanOccupiedBlocks();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
