package train_controller;

import train_controller.TrainController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.Timer;
import javax.swing.JSlider;

/**
 *
 * @author Daniel
 */
public class TrainControllerUI extends javax.swing.JFrame {

    /**
     * Creates new form TrainControllerUI
     */
    public TrainControllerUI(TrainController tc) {
        this.controller = tc;
        initComponents();
        myInitComponents();
        new Timer(50, task).start();

    }
    
    TrainController controller;
    boolean brakeEngagedStatus = true;
    DecimalFormat df = new DecimalFormat("#####0.0");


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        kiSlider = new javax.swing.JSlider();
        kpSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        KpLabel = new javax.swing.JLabel();
        KiLabel = new javax.swing.JLabel();
        ApplyButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        InfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CurrentSpeedLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CmdSpeedLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PowerLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RunningAuthLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CmdAuthLabel = new javax.swing.JLabel();
        PeripheralsPanel = new javax.swing.JPanel();
        LDoorsLabel = new javax.swing.JLabel();
        RDoorsLabel = new javax.swing.JLabel();
        LightsLabel = new javax.swing.JLabel();
        TempSlider = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        LightsToggle = new javax.swing.JToggleButton();
        LDoorsToggle = new javax.swing.JToggleButton();
        RDoorsToggle = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ControlPanel = new javax.swing.JPanel();
        SetSpeedSlider = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        BrakeToggle = new javax.swing.JToggleButton();
        ManualModeToggle = new javax.swing.JToggleButton();
        ManualModeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        kiSlider.setMajorTickSpacing(5);
        kiSlider.setMinorTickSpacing(1);
        kiSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        kiSlider.setPaintLabels(true);
        kiSlider.setPaintTicks(true);
        kiSlider.setSnapToTicks(true);
        kiSlider.setValue(2);
        kiSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kiSliderStateChanged(evt);
            }
        });

        kpSlider.setMajorTickSpacing(5);
        kpSlider.setMinorTickSpacing(1);
        kpSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        kpSlider.setPaintLabels(true);
        kpSlider.setPaintTicks(true);
        kpSlider.setSnapToTicks(true);
        kpSlider.setValue(98);
        kpSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                kpSliderStateChanged(evt);
            }
        });

        jLabel4.setText("Ki");

        jLabel8.setText("Kp");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 255, 102));
        jTextPane1.setText("Federal law prohibits unauthorized tampering.");
        jTextPane1.setToolTipText("");
        jScrollPane1.setViewportView(jTextPane1);

        KpLabel.setText("98");

        KiLabel.setText("2");

        ApplyButton.setText("Apply");
        ApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(KpLabel)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kpSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kiSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KiLabel)
                            .addComponent(jLabel4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ApplyButton)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kpSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(kiSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KpLabel)
                    .addComponent(KiLabel))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApplyButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);

        InfoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Speed (MPH)");

        jLabel2.setText("Auth (yds)");

        jLabel3.setText("Current");

        CurrentSpeedLabel.setText("0.0");

        jLabel5.setText("CMD");

        CmdSpeedLabel.setText("0.0");

        jLabel7.setText("Power kW");

        PowerLabel.setText("0.0");

        jLabel9.setText("Running");

        RunningAuthLabel.setText("0.0");

        jLabel11.setText("CMD");

        CmdAuthLabel.setText("0.0");

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(PowerLabel))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CmdSpeedLabel)
                            .addComponent(CurrentSpeedLabel))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CmdAuthLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RunningAuthLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(66, 66, 66))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CurrentSpeedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CmdSpeedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(PowerLabel)))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(RunningAuthLabel))
                        .addGap(13, 13, 13)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CmdAuthLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PeripheralsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LDoorsLabel.setText("C");

        RDoorsLabel.setText("C");

        LightsLabel.setText("OFF");

        TempSlider.setMajorTickSpacing(5);
        TempSlider.setMaximum(80);
        TempSlider.setMinimum(60);
        TempSlider.setMinorTickSpacing(1);
        TempSlider.setPaintLabels(true);
        TempSlider.setPaintTicks(true);
        TempSlider.setValue(70);

        jLabel16.setText("Set Temp");

        LightsToggle.setText("Lights");
        LightsToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LightsToggleActionPerformed(evt);
            }
        });

        LDoorsToggle.setText("L Doors");
        LDoorsToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDoorsToggleActionPerformed(evt);
            }
        });

        RDoorsToggle.setText("R Doors");
        RDoorsToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDoorsToggleActionPerformed(evt);
            }
        });

        jLabel6.setText("70 *F");

        jLabel10.setText("Current Temp:");

        javax.swing.GroupLayout PeripheralsPanelLayout = new javax.swing.GroupLayout(PeripheralsPanel);
        PeripheralsPanel.setLayout(PeripheralsPanelLayout);
        PeripheralsPanelLayout.setHorizontalGroup(
            PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                        .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                                .addComponent(LightsToggle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LightsLabel))
                            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeripheralsPanelLayout.createSequentialGroup()
                                        .addComponent(RDoorsToggle)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RDoorsLabel))
                                    .addComponent(TempSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel16)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeripheralsPanelLayout.createSequentialGroup()
                        .addComponent(LDoorsToggle)
                        .addGap(12, 12, 12)
                        .addComponent(LDoorsLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PeripheralsPanelLayout.setVerticalGroup(
            PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDoorsLabel)
                    .addComponent(RDoorsLabel)
                    .addComponent(LDoorsToggle)
                    .addComponent(RDoorsToggle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                        .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LightsLabel)
                            .addComponent(LightsToggle))
                        .addContainerGap())
                    .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                        .addComponent(TempSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)))))
        );

        ControlPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ControlPanel.setForeground(new java.awt.Color(255, 153, 0));

        SetSpeedSlider.setMajorTickSpacing(5);
        SetSpeedSlider.setMaximum(43);
        SetSpeedSlider.setMinorTickSpacing(1);
        SetSpeedSlider.setPaintLabels(true);
        SetSpeedSlider.setPaintTicks(true);
        SetSpeedSlider.setValue(0);
        SetSpeedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SetSpeedSliderStateChanged(evt);
            }
        });
        SetSpeedSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SetSpeedSliderMouseReleased(evt);
            }
        });

        jLabel17.setText("MPH Set");

        BrakeToggle.setSelected(true);
        BrakeToggle.setText("BRAKE");
        BrakeToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrakeToggleActionPerformed(evt);
            }
        });

        ManualModeToggle.setSelected(true);
        ManualModeToggle.setText("Manual Mode");
        ManualModeToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualModeToggleActionPerformed(evt);
            }
        });

        ManualModeLabel.setText("ON");

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SetSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(BrakeToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ControlPanelLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel17)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ManualModeToggle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(ManualModeLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManualModeToggle)
                    .addComponent(ManualModeLabel))
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BrakeToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Settings");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PeripheralsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeripheralsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myInitComponents()
    {
        menuItem = new javax.swing.JMenuItem("Set PI Params", KeyEvent.VK_T);
        jMenu1.add(menuItem);
        menuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                jDialog1.setVisible(true);
                jDialog1.setBounds(400,400,175,400);
            }
        });
    }
    
    private void SetSpeedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SetSpeedSliderStateChanged
        // TODO add your handling code here:
        JSlider source = (JSlider)evt.getSource();
        controller.setDriverSpeed(source.getValue());
    }//GEN-LAST:event_SetSpeedSliderStateChanged

    private void LDoorsToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDoorsToggleActionPerformed
        // TODO add your handling code here:
        if(LDoorsLabel.getText().equals("O"))
        {
            controller.setLeftDoors(false);
            LDoorsLabel.setText("C");
        }
        else
        {
            controller.setLeftDoors(true);
            LDoorsLabel.setText("O");
        }
    }//GEN-LAST:event_LDoorsToggleActionPerformed

    private void RDoorsToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDoorsToggleActionPerformed
        // TODO add your handling code here:
    if(RDoorsLabel.getText().equals("O"))
        {
            controller.setRightDoors(false);
            RDoorsLabel.setText("C");
        }
        else
        {
            controller.setRightDoors(true);
            RDoorsLabel.setText("O");
        }
    }//GEN-LAST:event_RDoorsToggleActionPerformed

    private void LightsToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LightsToggleActionPerformed
        // TODO add your handling code here:
    if(LightsLabel.getText().equals("OFF"))
        {
            controller.setLights(true);
            LightsLabel.setText("ON");
        }
        else
        {
            controller.setLights(false);
            LightsLabel.setText("OFF");
        }
    }//GEN-LAST:event_LightsToggleActionPerformed

    private void ManualModeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualModeToggleActionPerformed
        // TODO add your handling code here:
     if(ManualModeLabel.getText().equals("OFF"))
        {
            controller.setManualMode(true);
            ManualModeLabel.setText("ON");
        }
        else
        {
            controller.setManualMode(false);
            ManualModeLabel.setText("OFF");
        }
    }//GEN-LAST:event_ManualModeToggleActionPerformed

    private void BrakeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrakeToggleActionPerformed
        // TODO add your handling code here:
    if(brakeEngagedStatus)
        {
            controller.setBrakesEngaged(false);
            brakeEngagedStatus = false;
        }
        else
        {
            controller.setBrakesEngaged(true);
            brakeEngagedStatus = true;
        }
    }//GEN-LAST:event_BrakeToggleActionPerformed

    private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyButtonActionPerformed
        controller.setKs((double)kpSlider.getValue() / 100);
        jDialog1.setVisible(false);
    }//GEN-LAST:event_ApplyButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed
    
    private void kpSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kpSliderStateChanged
        kiSlider.setValue(100 - kpSlider.getValue());
        KpLabel.setText("" + kpSlider.getValue());
        KiLabel.setText("" + kiSlider.getValue());
    }//GEN-LAST:event_kpSliderStateChanged

    private void kiSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_kiSliderStateChanged
        kpSlider.setValue(100 - kiSlider.getValue());
    }//GEN-LAST:event_kiSliderStateChanged

    private void SetSpeedSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetSpeedSliderMouseReleased
        // TODO add your handling code here:
        JSlider source = (JSlider)evt.getSource();
        int s = source.getValue();
        double c = controller.getCTCspeed();
        controller.setDriverSpeed(s);
        if(s > c)
            source.setValue((int)c);
    }//GEN-LAST:event_SetSpeedSliderMouseReleased
 
    ActionListener task = new ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            CurrentSpeedLabel.setText(df.format(controller.getSpeed()) + " mph");
            CmdSpeedLabel.setText(df.format(controller.getCTCspeed()) + " mph");
            CmdAuthLabel.setText(df.format(controller.getCTCauth()) + " yds");
            RunningAuthLabel.setText(df.format(controller.getMovingAuth()) + " yds");
            PowerLabel.setText(df.format(controller.getPowerKW()) + " kW");
        }
    };
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    private javax.swing.JMenuItem menuItem;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApplyButton;
    private javax.swing.JToggleButton BrakeToggle;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CmdAuthLabel;
    private javax.swing.JLabel CmdSpeedLabel;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JLabel CurrentSpeedLabel;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JLabel KiLabel;
    private javax.swing.JLabel KpLabel;
    private javax.swing.JLabel LDoorsLabel;
    private javax.swing.JToggleButton LDoorsToggle;
    private javax.swing.JLabel LightsLabel;
    private javax.swing.JToggleButton LightsToggle;
    private javax.swing.JLabel ManualModeLabel;
    private javax.swing.JToggleButton ManualModeToggle;
    private javax.swing.JPanel PeripheralsPanel;
    private javax.swing.JLabel PowerLabel;
    private javax.swing.JLabel RDoorsLabel;
    private javax.swing.JToggleButton RDoorsToggle;
    private javax.swing.JLabel RunningAuthLabel;
    private javax.swing.JSlider SetSpeedSlider;
    private javax.swing.JSlider TempSlider;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JSlider kiSlider;
    private javax.swing.JSlider kpSlider;
    // End of variables declaration//GEN-END:variables
}
