package train_controller;

import train_controller.TrainController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.Timer;
import javax.swing.JSlider;

/**
 *
 * @author Daniel
 */
public class TrainControllerUI extends javax.swing.JFrame {
    
    ActionListener task = new ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            CurrentSpeedLabel.setText(df.format(controller.getSpeed()) + " mph");
            CmdSpeedLabel.setText(df.format(controller.getCTCspeed()) + " mph");
            CmdAuthLabel.setText(df.format(controller.getCTCauth()) + " yds");
            RunningAuthLabel.setText(df.format(controller.getMovingAuth()) + " yds");
            PowerLabel.setText(df.format(controller.getPowerKW()) + " kW");
            ActualTempLabel.setText(Integer.toString((int)controller.getTemp()));
            
            updateDoorLabels();
        }
    };
    /**
     * Creates new form TrainControllerUI
     */
    public TrainControllerUI(TrainController tc) {
        this.controller = tc;
        initComponents();
        myInitComponents();
        new Timer(50, task).start();
    }
    
    TrainController controller;
    boolean brakeEngagedStatus = true;
    DecimalFormat df = new DecimalFormat("#####0.0");


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
	setTitle("Train Controller");
        jDialog1 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ApplyButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        KpTextField = new javax.swing.JTextField();
        KiTextField = new javax.swing.JTextField();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        InfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CurrentSpeedLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CmdSpeedLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PowerLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RunningAuthLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CmdAuthLabel = new javax.swing.JLabel();
        PeripheralsPanel = new javax.swing.JPanel();
        LDoorsLabel = new javax.swing.JLabel();
        RDoorsLabel = new javax.swing.JLabel();
        LightsLabel = new javax.swing.JLabel();
        TempSlider = new javax.swing.JSlider();
        jLabel16 = new javax.swing.JLabel();
        LightsToggle = new javax.swing.JToggleButton();
        ActualTempLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LeftDoorButton = new javax.swing.JButton();
        RightDoorButton = new javax.swing.JButton();
        ControlPanel = new javax.swing.JPanel();
        SetSpeedSlider = new javax.swing.JSlider();
        jLabel17 = new javax.swing.JLabel();
        ManualModeToggle = new javax.swing.JToggleButton();
        ManualModeLabel = new javax.swing.JLabel();
        BrakeLabel = new javax.swing.JLabel();
        BrakeButton = new javax.swing.JButton();
        EmergencyPanel = new javax.swing.JPanel();
        EmergencyBrakeButton = new javax.swing.JButton();
        EmergencyBrakeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jLabel4.setText("Ki");

        jLabel8.setText("Kp");

        jTextPane1.setEditable(false);
        jTextPane1.setBackground(new java.awt.Color(255, 255, 102));
        jTextPane1.setText("Federal law prohibits unauthorized tampering. Default values: Kp=0.98, Ki=0.02");
        jTextPane1.setToolTipText("");
        jScrollPane1.setViewportView(jTextPane1);

        ApplyButton.setText("Apply");
        ApplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplyButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        KpTextField.setText("0.98");
        KpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KpTextFieldActionPerformed(evt);
            }
        });

        KiTextField.setText("0.02");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(KpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(KiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(CancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ApplyButton))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(ApplyButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextPane2.setEditable(false);
        jTextPane2.setText("Error: Kp and Ki can only be changed before train begins moving. ");
        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.black);

        InfoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Speed (MPH)");

        jLabel2.setText("Auth (yds)");

        jLabel3.setText("Current");

        CurrentSpeedLabel.setText("0.0");

        jLabel5.setText("CMD");

        CmdSpeedLabel.setText("0.0");

        jLabel7.setText("Power kW");

        PowerLabel.setText("0.0");

        jLabel9.setText("Running");

        RunningAuthLabel.setText("0.0");

        jLabel11.setText("CMD");

        CmdAuthLabel.setText("0.0");

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(PowerLabel))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CmdSpeedLabel)
                            .addComponent(CurrentSpeedLabel))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CmdAuthLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RunningAuthLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(66, 66, 66))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CurrentSpeedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CmdSpeedLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(PowerLabel)))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(RunningAuthLabel))
                        .addGap(13, 13, 13)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CmdAuthLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PeripheralsPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        LDoorsLabel.setText("C");

        RDoorsLabel.setText("C");

        LightsLabel.setText("OFF");

        TempSlider.setMajorTickSpacing(5);
        TempSlider.setMaximum(80);
        TempSlider.setMinimum(60);
        TempSlider.setMinorTickSpacing(1);
        TempSlider.setPaintLabels(true);
        TempSlider.setPaintTicks(true);
        TempSlider.setValue(70);
        TempSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TempSliderStateChanged(evt);
            }
        });

        jLabel16.setText("Set Temp");

        LightsToggle.setText("Lights");
        LightsToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LightsToggleActionPerformed(evt);
            }
        });

        ActualTempLabel.setText("70 *F");

        jLabel10.setText("Current Temp:");

        LeftDoorButton.setText("L Doors");
        LeftDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftDoorButtonActionPerformed(evt);
            }
        });

        RightDoorButton.setText("R Doors");
        RightDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightDoorButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PeripheralsPanelLayout = new javax.swing.GroupLayout(PeripheralsPanel);
        PeripheralsPanel.setLayout(PeripheralsPanelLayout);
        PeripheralsPanelLayout.setHorizontalGroup(
            PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                        .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                                .addComponent(LightsToggle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LightsLabel))
                            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ActualTempLabel)))
                        .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeripheralsPanelLayout.createSequentialGroup()
                                        .addComponent(RightDoorButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RDoorsLabel))
                                    .addComponent(TempSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel16)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PeripheralsPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(LeftDoorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LDoorsLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PeripheralsPanelLayout.setVerticalGroup(
            PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDoorsLabel)
                    .addComponent(RDoorsLabel)
                    .addComponent(LeftDoorButton)
                    .addComponent(RightDoorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                        .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LightsLabel)
                            .addComponent(LightsToggle))
                        .addContainerGap())
                    .addGroup(PeripheralsPanelLayout.createSequentialGroup()
                        .addComponent(TempSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(PeripheralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ActualTempLabel)
                            .addComponent(jLabel10)))))
        );

        ControlPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ControlPanel.setForeground(new java.awt.Color(255, 153, 0));

        SetSpeedSlider.setMajorTickSpacing(5);
        SetSpeedSlider.setMaximum(43);
        SetSpeedSlider.setMinorTickSpacing(1);
        SetSpeedSlider.setPaintLabels(true);
        SetSpeedSlider.setPaintTicks(true);
        SetSpeedSlider.setValue(0);
        SetSpeedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SetSpeedSliderStateChanged(evt);
            }
        });
        SetSpeedSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SetSpeedSliderMouseReleased(evt);
            }
        });

        jLabel17.setText("MPH Set");

        ManualModeToggle.setSelected(true);
        ManualModeToggle.setText("Manual Mode");
        ManualModeToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualModeToggleActionPerformed(evt);
            }
        });

        ManualModeLabel.setText("ON");

        BrakeLabel.setText("ON");

        BrakeButton.setText("BRAKE");
        BrakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrakeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SetSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(BrakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BrakeLabel))
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ControlPanelLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(jLabel17)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ControlPanelLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(ManualModeToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(ManualModeLabel)
                        .addGap(47, 47, 47)))
                .addGap(10, 10, 10))
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManualModeToggle)
                    .addComponent(ManualModeLabel))
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SetSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BrakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrakeLabel))
                .addGap(16, 16, 16))
        );

        EmergencyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        EmergencyBrakeButton.setForeground(new java.awt.Color(255, 51, 51));
        EmergencyBrakeButton.setText("EMERGENCY BRAKE");
        EmergencyBrakeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyBrakeButtonActionPerformed(evt);
            }
        });

        EmergencyBrakeLabel.setText("READY");

        javax.swing.GroupLayout EmergencyPanelLayout = new javax.swing.GroupLayout(EmergencyPanel);
        EmergencyPanel.setLayout(EmergencyPanelLayout);
        EmergencyPanelLayout.setHorizontalGroup(
            EmergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmergencyBrakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(EmergencyPanelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(EmergencyBrakeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmergencyPanelLayout.setVerticalGroup(
            EmergencyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmergencyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmergencyBrakeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmergencyBrakeLabel)
                .addContainerGap())
        );

        jMenu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Settings");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PeripheralsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmergencyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PeripheralsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmergencyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myInitComponents()
    {
        menuItem = new javax.swing.JMenuItem("Set PI Params", KeyEvent.VK_T);
        jMenu1.add(menuItem);
        menuItem.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if(controller.getAllowKSet())
                {
                    jDialog1.setVisible(true);
                    jDialog1.setBounds(400,400,200,300);
                }
                else
                {
                    jDialog2.setVisible(true);
                    jDialog2.setBounds(400,400,250,120);
                }
            }
        });
    }
    
    private void updateDoorLabels()
    {
        int i = controller.getDoorStates();
        switch (i) {
            case 0:     LDoorsLabel.setText("C");
                        RDoorsLabel.setText("C");
                        break;
            case 1:     LDoorsLabel.setText("C");
                        RDoorsLabel.setText("O");
                        break;
            case 2:     LDoorsLabel.setText("O");
                        RDoorsLabel.setText("C");
                        break;
            case 3:     LDoorsLabel.setText("O");
                        RDoorsLabel.setText("O");
                        break;
        }
    }
    
    private void SetSpeedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SetSpeedSliderStateChanged
        // TODO add your handling code here:
        JSlider source = (JSlider)evt.getSource();
        controller.setDriverSpeed(source.getValue());
    }//GEN-LAST:event_SetSpeedSliderStateChanged

    private void LightsToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LightsToggleActionPerformed
        // TODO add your handling code here:
    if(LightsLabel.getText().equals("OFF"))
        {
            controller.setLights(true);
            LightsLabel.setText("ON");
        }
        else
        {
            controller.setLights(false);
            LightsLabel.setText("OFF");
        }
    }//GEN-LAST:event_LightsToggleActionPerformed

    private void ManualModeToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualModeToggleActionPerformed
        // TODO add your handling code here:
     if(ManualModeLabel.getText().equals("OFF"))
        {
            controller.setManualMode(true);
            ManualModeLabel.setText("ON");
        }
        else
        {
            controller.setManualMode(false);
            ManualModeLabel.setText("OFF");
        }
    }//GEN-LAST:event_ManualModeToggleActionPerformed

    private void ApplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplyButtonActionPerformed
        controller.setKs(Double.parseDouble(KpTextField.getText()), Double.parseDouble(KiTextField.getText()));
        jDialog1.setVisible(false);
    }//GEN-LAST:event_ApplyButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_CancelButtonActionPerformed
    
    private void SetSpeedSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetSpeedSliderMouseReleased
        // TODO add your handling code here:
        JSlider source = (JSlider)evt.getSource();
        int s = source.getValue();
        double c = controller.getCTCspeed();
        controller.setDriverSpeed(s);
        if(s > c)
            if((int)c < c)
                source.setValue((int)c + 1);
            else
                source.setValue((int)c);
    }//GEN-LAST:event_SetSpeedSliderMouseReleased

    private void BrakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrakeButtonActionPerformed
        // TODO add your handling code here:
    if(brakeEngagedStatus)
        {
            controller.setBrakesEngaged(false);
            brakeEngagedStatus = false;
            if(ManualModeLabel.getText().equals("ON"))
            {
                BrakeLabel.setText("OFF");
            }
            else
                BrakeLabel.setText("OFF (wait)");
        }
        else
        {
            controller.setBrakesEngaged(true);
            brakeEngagedStatus = true;
            if(ManualModeLabel.getText().equals("ON"))
            {
                BrakeLabel.setText("ON");           
            }
            else
                BrakeLabel.setText("ON (wait)");           
        }
    }//GEN-LAST:event_BrakeButtonActionPerformed

    private void EmergencyBrakeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyBrakeButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EmergencyBrakeButtonActionPerformed

    private void KpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KpTextFieldActionPerformed

    private void TempSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TempSliderStateChanged
        // TODO add your handling code here:
        controller.setTemp(TempSlider.getValue());
    }//GEN-LAST:event_TempSliderStateChanged

    private void LeftDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftDoorButtonActionPerformed
        // TODO add your handling code here:
        if(LDoorsLabel.getText().equals("O"))
        {
            controller.setLeftDoors(false);
            LDoorsLabel.setText("C");
        }
        else
        {
            controller.setLeftDoors(true);
            LDoorsLabel.setText("O");
        }
    }//GEN-LAST:event_LeftDoorButtonActionPerformed

    private void RightDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightDoorButtonActionPerformed
        // TODO add your handling code here:
        if(RDoorsLabel.getText().equals("O"))
        {
            controller.setRightDoors(false);
            RDoorsLabel.setText("C");
        }
        else
        {
            controller.setRightDoors(true);
            RDoorsLabel.setText("O");
        }        
    }//GEN-LAST:event_RightDoorButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainControllerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    private javax.swing.JMenuItem menuItem;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActualTempLabel;
    private javax.swing.JButton ApplyButton;
    private javax.swing.JButton BrakeButton;
    private javax.swing.JLabel BrakeLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CmdAuthLabel;
    private javax.swing.JLabel CmdSpeedLabel;
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JLabel CurrentSpeedLabel;
    private javax.swing.JButton EmergencyBrakeButton;
    private javax.swing.JLabel EmergencyBrakeLabel;
    private javax.swing.JPanel EmergencyPanel;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JTextField KiTextField;
    private javax.swing.JTextField KpTextField;
    private javax.swing.JLabel LDoorsLabel;
    private javax.swing.JButton LeftDoorButton;
    private javax.swing.JLabel LightsLabel;
    private javax.swing.JToggleButton LightsToggle;
    private javax.swing.JLabel ManualModeLabel;
    private javax.swing.JToggleButton ManualModeToggle;
    private javax.swing.JPanel PeripheralsPanel;
    private javax.swing.JLabel PowerLabel;
    private javax.swing.JLabel RDoorsLabel;
    private javax.swing.JButton RightDoorButton;
    private javax.swing.JLabel RunningAuthLabel;
    private javax.swing.JSlider SetSpeedSlider;
    private javax.swing.JSlider TempSlider;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
