/*
 * Ryan Matthews
 *
 * Main UI
 *
 * Can open CTC, MBO, and track UIs
 *
 * NOTE:
 *   Has automagically generated code from Netbeans GUI editor. Doesn't match
 *   our style conventions.
 */

package integration;

// FIXME: see Main imports
import ctc.Ctc;
import track_model.TrackModel;
import train_model.TrainModel;
import train_controller.TrainController;

import train_model.communication.TrackMovementCommand;

/**
 *
 * @author ryan
 */
public class UI extends javax.swing.JFrame {

    // FIXME: see imports
    private Ctc ctc;
    private TrackModel trackModel;
    private TrainModel[] trainModels;
    private TrainController[] trainControllers;

    /**
     * Creates new form UI
     */
    public UI(Ctc ctc, TrackModel trackModel, TrainModel[] trainModels,
              TrainController[] trainControllers) {
        this.ctc = ctc;
        this.trackModel = trackModel;
        this.trainModels = trainModels;
        this.trainControllers = trainControllers;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ctcButton = new javax.swing.JButton();
        trackModelButton = new javax.swing.JButton();
        trainModelButton = new javax.swing.JButton();
        trainControllerButton = new javax.swing.JButton();
        trainId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ctcButton.setText("CTC");
        ctcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctcButtonActionPerformed(evt);
            }
        });

        trackModelButton.setText("Track Model");
        trackModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackModelButtonActionPerformed(evt);
            }
        });

        trainModelButton.setText("Train Model");
        trainModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainModelButtonActionPerformed(evt);
            }
        });

        trainControllerButton.setText("Train Controller");
        trainControllerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainControllerButtonActionPerformed(evt);
            }
        });

        trainId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        trainId.setText("0");
        trainId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Train ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctcButton)
                    .addComponent(trainControllerButton)
                    .addComponent(trackModelButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trainId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(trainModelButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctcButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trackModelButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(trainId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trainModelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trainControllerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctcButtonActionPerformed
        // TODO add your handling code here:
        ctc.showUI();
    }//GEN-LAST:event_ctcButtonActionPerformed

    private void trackModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackModelButtonActionPerformed
        // TODO add your handling code here:
        trackModel.launchUI();
    }//GEN-LAST:event_trackModelButtonActionPerformed

    private void trainModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainModelButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(trainId.getText());
        new train_model.subsystem_demo.UI(trainModels[id]).setVisible(true);
    }//GEN-LAST:event_trainModelButtonActionPerformed

    private void trainControllerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainControllerButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(trainId.getText());
        trainControllers[id].launchGUI();
    }//GEN-LAST:event_trainControllerButtonActionPerformed

    private void trainIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trainIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // TODO
                //new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ctcButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton trackModelButton;
    private javax.swing.JButton trainControllerButton;
    private javax.swing.JTextField trainId;
    private javax.swing.JButton trainModelButton;
    // End of variables declaration//GEN-END:variables
}
